# Generated by Django 2.2.4 on 2019-08-25 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('School', models.CharField(max_length=50)),
                ('Project_Type', models.CharField(max_length=50)),
                ('Cohort', models.CharField(max_length=50)),
                ('Partner_Agency', models.CharField(max_length=50)),
            ],
        ),
    ]
