# Generated by Django 2.2.4 on 2019-09-15 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refrelief', '0005_auto_20190909_0156'),
    ]

    operations = [
        migrations.CreateModel(
            name='Communitycourse',
            fields=[
                ('index', models.AutoField(primary_key=True, serialize=False)),
                ('class_name', models.TextField(blank=True, db_column='class name', null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('contact', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('field_start_time', models.TextField(blank=True, db_column=' Start Time', null=True)),
                ('end_time', models.TextField(blank=True, db_column='End Time', null=True)),
                ('weekday', models.TextField(blank=True, null=True)),
                ('community', models.TextField(blank=True, db_column='Community', null=True)),
                ('suburb', models.TextField(blank=True, db_column='Suburb', null=True)),
                ('country', models.TextField(blank=True, db_column='Country', null=True)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lng', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'communitycourse',
                'managed': False,
            },
        ),
    ]
