# Generated by Django 2.2.4 on 2019-10-20 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refrelief', '0008_auto_20190917_0020'),
    ]

    operations = [
        migrations.CreateModel(
            name='Distance',
            fields=[
                ('index', models.AutoField(primary_key=True, serialize=False)),
                ('distance', models.TextField(blank=True, null=True)),
                ('explain', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'distance',
                'managed': False,
            },
        ),
    ]
